# Class

## Goal
- Memperkenalkan library python untuk pengolahan data berbentuk matrix

## Referensi
- https://cs231n.github.io/python-numpy-tutorial/

### 1. Numpy - Basic

In [5]:
import numpy as np

1. List adalah suatu object yang dapat menampung lebih dari satu object.
2. List dapat memuat object list.
3. Array adalah suatu object yang dapat menampung lebih dari 1 object yang homogen dan memiliki dimensi sebanyak n. 
4. Matrix adalah suatu object yang dapat menampung lebih dari 1 object yang homogen dan memiliki dimensi 2. Matrix adalah subset dari Array.
5. Numpy adalah tools untuk memproses array.

In [53]:
# list object
list_obj = [1, 2, 3]
list_obj

[1, 2, 3]

In [54]:
len(list_obj)

3

In [58]:
# array object dengan 1 dimensi berukuran 3
arr_obj = np.array(list_obj)
arr_obj

array([1, 2, 3])

In [59]:
len(arr_obj)

3

In [60]:
arr_obj.shape

(3,)

In [68]:
# array object dengan 2 dimensi berukuran 1 x 3
mtx_obj = np.matrix(list_obj)
mtx_obj

matrix([[1, 2, 3]])

In [69]:
mtx_obj.shape

(1, 3)

In [72]:
# array object dengan 2 dimensi berukuran 3 x 1
mtx_obj_reshape = mtx_obj.reshape(3,-1)
mtx_obj_reshape

matrix([[1],
        [2],
        [3]])

In [73]:
mtx_obj_reshape.shape

(3, 1)

In [76]:
# list object
list_obj = [1, 2, 'test']
list_obj

[1, 2, 'test']

In [77]:
# array object dengan 1 dimensi berukuran 3
arr_obj = np.array(list_obj)
arr_obj

array(['1', '2', 'test'], dtype='<U21')

In [78]:
# list object
list_obj = [1, 2, ['test']]
list_obj

[1, 2, ['test']]

In [79]:
# array object dengan 1 dimensi berukuran 3
arr_obj = np.array(list_obj)
arr_obj

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [80]:
# list object
list_obj = [[1], [2], ['test']]
list_obj

[[1], [2], ['test']]

In [81]:
# array object dengan 1 dimensi berukuran 3
arr_obj = np.array(list_obj)
arr_obj

array([['1'],
       ['2'],
       ['test']], dtype='<U21')

### 2. Numpy - Array Generator

In [92]:
# Method yang mengenerate matrix nilai 0
a = np.zeros((3,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [93]:
# Method yang mengenerate matrix nilai 1
a = np.ones((3,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [94]:
# Method yang mengenerate matrix identitas (matrix dengan nilai 1 pada diagonal line)
a = np.eye((3))
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [95]:
# Method yang mengenerate matrix dengan nilai sesuai yang diinginkan pada seluruh element matrix
a = np.full((3,3), 6)
print(a)

[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [96]:
# Method yang mengenerate matrix dengan nilai random
a = np.random.random((3,3))
print(a)

[[0.9605407  0.32227612 0.55847449]
 [0.52744259 0.73945882 0.04596852]
 [0.05471021 0.67438519 0.26358844]]


### 2. Numpy - Array Selection

In [112]:
mtx_obj = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
mtx_obj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [113]:
mtx_obj.shape

(4, 4)

In [114]:
mtx_obj[0, :]

array([1, 2, 3, 4])

In [115]:
mtx_obj[1, :]

array([5, 6, 7, 8])

In [116]:
mtx_obj[2, :]

array([ 9, 10, 11, 12])

In [117]:
mtx_obj[3, :]

array([13, 14, 15, 16])

In [118]:
mtx_obj[4, :]

IndexError: index 4 is out of bounds for axis 0 with size 4

In [120]:
mtx_obj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [119]:
mtx_obj[:, 0]

array([ 1,  5,  9, 13])

In [121]:
mtx_obj[:, 1]

array([ 2,  6, 10, 14])

In [122]:
mtx_obj[:, 2]

array([ 3,  7, 11, 15])

In [123]:
mtx_obj[:, 3]

array([ 4,  8, 12, 16])

In [124]:
mtx_obj[:, 4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [125]:
mtx_obj

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [132]:
mtx_obj[1:,1:]

array([[ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [127]:
mtx_obj[:-1,:-1]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [128]:
mtx_obj[1:-1,1:-1]

array([[ 6,  7],
       [10, 11]])

In [129]:
mtx_obj[[0,3], :]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

In [136]:
mtx_obj[:, [1,3]]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [137]:
mtx_obj[[2,3], [1,3]]

array([10, 16])

### 3. Numpy - Array Operations

In [211]:
### Operasi skalar

In [180]:
mtx_obj_1 = np.array([[1,2],[3,4],[5,6]])
mtx_obj_1

array([[1, 2],
       [3, 4],
       [5, 6]])

In [181]:
mtx_obj_1.shape

(3, 2)

In [182]:
mtx_obj_1 * 2

array([[ 2,  4],
       [ 6,  8],
       [10, 12]])

In [183]:
mtx_obj_1 + 2

array([[3, 4],
       [5, 6],
       [7, 8]])

In [184]:
mtx_obj_1 - 2

array([[-1,  0],
       [ 1,  2],
       [ 3,  4]])

In [185]:
mtx_obj_1 / 2

array([[0.5, 1. ],
       [1.5, 2. ],
       [2.5, 3. ]])

In [214]:
### Operasi matrix

In [186]:
mtx_obj_2 = np.array([[7,8],[9,10],[11,12]])
mtx_obj_2

array([[ 7,  8],
       [ 9, 10],
       [11, 12]])

In [187]:
mtx_obj_2.shape

(3, 2)

In [189]:
print(mtx_obj_1)
print()
print(mtx_obj_2)
print()

mtx_obj_1 + mtx_obj_2

[[1 2]
 [3 4]
 [5 6]]

[[ 7  8]
 [ 9 10]
 [11 12]]



array([[ 8, 10],
       [12, 14],
       [16, 18]])

In [215]:
### Operasi matrix dengan broadcasting

In [195]:
print(mtx_obj_1)
print('ukuran matrix {}'.format(mtx_obj_1.shape))
print()
print(mtx_obj_2[0,:])
print('ukuran matrix {}'.format(mtx_obj_2[0,:].shape))
print()

mtx_obj_1 + mtx_obj_2[0,:]

[[1 2]
 [3 4]
 [5 6]]
ukuran matrix (3, 2)

[7 8]
ukuran matrix (2,)



array([[ 8, 10],
       [10, 12],
       [12, 14]])

In [198]:
print(mtx_obj_1)
print('ukuran matrix {}'.format(mtx_obj_1.shape))
print()
print(mtx_obj_2[:,0])
print('ukuran matrix {}'.format(mtx_obj_2[:,0].shape))
print()

mtx_obj_1 + mtx_obj_2[:,0]

[[1 2]
 [3 4]
 [5 6]]
ukuran matrix (3, 2)

[ 7  9 11]
ukuran matrix (3,)



ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [196]:
print(mtx_obj_1)
print('ukuran matrix {}'.format(mtx_obj_1.shape))
print()
print(mtx_obj_2[0,:])
print('ukuran matrix {}'.format(mtx_obj_2[0,:].shape))
print()

mtx_obj_1 * mtx_obj_2[0,:]

[[1 2]
 [3 4]
 [5 6]]
ukuran matrix (3, 2)

[7 8]
ukuran matrix (2,)



array([[ 7, 16],
       [21, 32],
       [35, 48]])

In [197]:
print(mtx_obj_1)
print('ukuran matrix {}'.format(mtx_obj_1.shape))
print()
print(mtx_obj_2[:,0])
print('ukuran matrix {}'.format(mtx_obj_2[:,0].shape))
print()

mtx_obj_1 * mtx_obj_2[:,0]

[[1 2]
 [3 4]
 [5 6]]
ukuran matrix (3, 2)

[ 7  9 11]
ukuran matrix (3,)



ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [205]:
print(mtx_obj_1)
print('ukuran matrix {}'.format(mtx_obj_1.shape))
print()
print(mtx_obj_2[1:,:])
print('ukuran matrix {}'.format(mtx_obj_2[1:,:].shape))
print()

mtx_obj_1 + mtx_obj_2[1:,:]

[[1 2]
 [3 4]
 [5 6]]
ukuran matrix (3, 2)

[[ 9 10]
 [11 12]]
ukuran matrix (2, 2)



ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [216]:
### Perkalian Matrix

In [210]:
print(mtx_obj_1)
print('ukuran matrix {}'.format(mtx_obj_1.shape))
print()
print(mtx_obj_2[1:,:])
print('ukuran matrix {}'.format(mtx_obj_2[1:,:].shape))
print()

mtx_obj_1.dot(mtx_obj_2[1:,:])

[[1 2]
 [3 4]
 [5 6]]
ukuran matrix (3, 2)

[[ 9 10]
 [11 12]]
ukuran matrix (2, 2)



array([[ 31,  34],
       [ 71,  78],
       [111, 122]])

In [172]:
print(mtx_obj_1)
print()
print('ukuran matrix {}.'.format(mtx_obj_1.shape))

[[1 2]
 [3 4]
 [5 6]]

ukuran matrix (3, 2).


In [173]:
print(mtx_obj_2[0,:])
print()
print('ukuran matrix {}.'.format(mtx_obj_2[0,:].shape))

[7 8]

ukuran matrix (2,).


In [174]:
mtx_obj_1 + mtx_obj_2[:,0]

ValueError: operands could not be broadcast together with shapes (3,2) (3,) 

In [175]:
print(mtx_obj_1)
print()
print('ukuran matrix {}.'.format(mtx_obj_1.shape))

[[1 2]
 [3 4]
 [5 6]]

ukuran matrix (3, 2).


In [176]:
print(mtx_obj_2[:,0])
print()
print('ukuran matrix {}.'.format(mtx_obj_2[:,0].shape))

[ 7  9 11]

ukuran matrix (3,).


In [179]:
mtx_obj_1.reshape(2,3) + mtx_obj_2[:,0]

array([[ 8, 11, 14],
       [11, 14, 17]])

### 4. Numpy - Additional

In [227]:
# start, stop, num of element
np.linspace(0, 100, 20)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])

In [229]:
# start, stop, step between element
np.arange(0, 100, 20)

array([ 0, 20, 40, 60, 80])

In [233]:
# Generate random number
np.random.rand(5)

array([0.50624314, 0.48392158, 0.71223417, 0.07494517, 0.10859404])

In [234]:
np.random.rand(5)

array([0.83147667, 0.07009502, 0.0271672 , 0.4751745 , 0.38869568])

In [236]:
# Generate persistent random number
np.random.seed(10)
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [238]:
np.random.seed(10)
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [241]:
np.random.seed(10)
np.random.randint(9)

4

In [242]:
np.random.seed(10)
np.random.randint(1, 10, 9)

array([5, 1, 2, 1, 2, 9, 1, 9, 7])

In [245]:
np.random.seed(10)
mtx_obj = np.random.randint(1, 10, 9).reshape(3,3)
mtx_obj

array([[5, 1, 2],
       [1, 2, 9],
       [1, 9, 7]])

In [246]:
# Replace value of matrix with condition
np.where(mtx_obj > 4, 1, 0)

array([[1, 0, 0],
       [0, 0, 1],
       [0, 1, 1]])

In [247]:
np.where(mtx_obj > 4, 0, mtx_obj)

array([[0, 1, 2],
       [1, 2, 0],
       [1, 0, 0]])

In [255]:
# Find index of max value in matrix
np.argmax(mtx_obj)

5

In [249]:
np.max(mtx_obj)

9